### PR TITLE
Add XPS introduction

### PR DESCRIPTION
**Pull request by nencypd**

### CODE REVIEW

**Comment by kjappelbaum** [comment]
@nencypd if you want to add links, there should not be a space between `[]` and `()`. 
You can check the link in the preview

**Comment by kjappelbaum** [comment]
but otherwise lgtm!

**Comment by kjappelbaum** [comment]
I think i confused you. You wanted to probably add wikipedia as reference but in this case you would use something like https://stackoverflow.com/questions/26587527/cite-a-paper-using-github-markdown-syntax where you have a link to an item in a reference section. 

In this case, I'd just use the word `XPS` as alt text and link to Wikipedia for further reference. We would only need a real citation if you copy-pasted wikipedia into the text here

**Comment by nencypd** [comment]
Ok, thank you, I will do that from now on

**Comment by kjappelbaum** [comment]
@nencypd I'll merge your PRs now so there are no conflicts while the other students continue working on it. After your holidays just pull from upstream and make new branches and PRs

**Pull request merged**
